### PR TITLE
Release SwE Version 1.2.9

### PR DESCRIPTION
**Pull request by TomMaullin**
#### Changes made since previous version

 - dev: Code restructure to delete duplicated sections.
 - fix: Output has been named consistently.
 - dev: Travis continuous integration testing added.
 - enh: Output is now displayed for wild bootstrap analyses.
 - enh: GUI options for display updated to be consistent with other toolboxes.
 - fix: An error is now thrown if a model has no intercept.
 - fix: The unrestricted wild bootstrap option has been removed.
 - fix: The correct images are now deleted on each run.
 - fix: The latex interpreter for column names on the design matrix display has been turned off.
 - enh: A footer has been added to the SwE display.

#### Link to relevant issues

 - Issue #3 
 - Issue #4 
 - Issue #6 
 - Issue #8 
 - Issue #9 
 - Issue #16 
 - Issue #17 
 - Issue #18 
 - Issue #24 
 - Issue #26 
 - Issue #27 
 - Issue #28 
 - Issue #36

### CODE REVIEW

**Comment by TomMaullin** [comment]
The tests have been paused as the Travis Cache is playing up due to there being different files in the `FooterCreation` branch's cache and the `master` branch cache. Hopefully this should be resolved once PR #34 is merged.

**Comment by nicholst** [comment]
Ok. I'm happy to merge when your happy.
-- 
_________________________________________________________
Thomas Nichols, PhD
Professor of Neuroimaging Statistics
Nuffield Department of Population Health | University of Oxford
Big Data Institute | Li Ka Shing Centre for Health Information and Discovery
Old Road Campus | Headington | Oxford | OX3 7LF | United Kingdom
T: +44 1865 743590 | E: thomas.nichols@bdi.ox.ac.uk
W: http://nisox.org | http://www.bdi.ox.ac.uk

**Comment by TomMaullin** [comment]
Hi @nicholst ,

We first would have to merge PR #34 as PR #34 includes the footer updates - and also an updated Travis Cache (we added the error degree of freedom maps but they aren't cached properly on Travis yet). Is it okay to merge PR #34 ?

**Comment by nicholst** [comment]
I understand you've left on holiday before this could go out... but please fire it off when ready.

**Pull request merged**
