### PR TITLE
GUI update

### PR DESCRIPTION
**Pull request by TomMaullin**
This PR updates the SwE GUI and addresses issue #29 by creating an interface similar to that of SnPM's.

### CODE REVIEW

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I have now made a new GUI based on that of SnPM's which looks something like the below:

image

I have also added the following features:

 - The 'Documentation' button which opens the NISOx website for SwE (The main reason I have added this was for the layout).
 - Two '?' buttons which open the comment sections added in PR #43 for reference. This minics the behavior of the previous SnPM menus.
 - The version number is also now displayed in the menu window for the users reference.

Please let me know what you think of these modifications and/or if you want anything to be changed/removed.

I am still waiting on the tests to run (the previous two runs failed because I stopped them manually myself) but please if you have a moment let me know what you think of the menu design and if possible whether it runs well on your mac as well.

Also included in this PR is the change to `swe_design` we have been discussing via email.

**Comment by nicholst** [comment]
Looks good.  Only comment is totally superficial... the colors are garish!  

Can we inherit the SnPM colors?  Having the color set as a call to swe also seems sensible:
```matlab
elseif strcmp(lower(Action),lower('Colour'))
%=======================================================================
% snpm('Colour')
%-----------------------------------------------------------------------
% %-Developmental livery
% varargout = {[0.7,1.0,0.7], 'Lime Green'};
%-Distribution livery
varargout = {[0.8 0.8 1.0], 'Diluted Blackcurrent Purple'};
```
where we set `'BackgroundColor',swe('Colour')`

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I have entered the colourscheme found in the SnPM code you sent and this is the resultant interface. I just thought I had best confirm, is this the colourscheme you' had in mind?

image

**Comment by TomMaullin** [comment]
Hi @nicholst ,

As all tests pass, so long as the above colour scheme is what you wanted, this PR is now ready for review! Please let me know what you think of the new GUI and batch options. I had to rename a few files to try and make the code layout consistent also - please let me know if you have any thoughts/suggestions/improvements and if you have a moment to try it out, whether everything runs correctly on Mac! Just to sum up what has changed in this PR:

 - The new interface has been added, which now includes:
   - The 'Documentation' button which opens the NISOx website for SwE in the matlab browser.
   - Two '?' buttons which open the comment sections added in PR #43 for reference.
   - The version number displayed in the menu window.
 - All SwE inputs now run through the batch window (with the exception of part of the `results display` section which we discussed has to be dynamic).
 - SwE can now be run as a toolbox through the SPM toolbox menu.

**Comment by nicholst** [comment]
Fantastic!!  This is what I always wanted!

Just one issue: When I click 'Run Model'  the Batch system asks me for *both* the directory and the SwE file, but the Directory has already been specified.  Can you eliminate that?

BTW, it looks different for me on a Mac (see below) but I'm really not fussed (don't worry about it).

Fix the double-entry of directory and this can get merged!

screen shot 2018-09-06 at 17 02 05

**Pull request merged**
