### PR TITLE
Release SwE Version 2.2.1

### PR DESCRIPTION
**Pull request by BryanGuillaume**
### Changes made since the previous version (v2.2.0)

- enh: modify the way non-parametric cluster-wise inference is performed for all types of inputs by using, when possible, Box-Cox normalized cluster extents instead of traditional cluster extents
- enh: remove the possibility to Box-Cox normalize the cluster extents using the mean and the standard deviation of the Box-Cox transformed cluster extents
- enh: add helper functions related to the Box-Cox normalization
- enh: invert the order of the sub-options for cluster-wise inference
- enh: add an option allowing the user to add a surface area file for GIfTI inputs
- enh: update some function headers
- enh: replace some recent Matlab functions or syntaxes to enable the compatibility of the SwE toolbox with old Matlab versions
- enh: use a consistent naming for `.mat` results across parametric and non-parametric analyses
- enh: improve the helper text of some options of the SwE model specification batch module
- enh: display a more visually appealing version of the design matrix in the result display window
- enh: improve the specification of t- and f-contrasts for Wild Bootstrap analyses
- fix: fix a bug occurring when a chunk of data would be entirely masked out
- fix: fix a bug occurring when writing GIfTI files in Octave
- fix: fix a bug related to the automatic masking of CIfTI and GIfTI analyses
- fix: fix a bug in the computation of X-scores for `.mat` inputs
- fix: fix a bug for `.mat` inputs where `spm_mesh_detect` would not work for empty cell arrays
- fix: fix a bug where some results for `.mat` analyses would not be saved correctly
- fix: fix a bug occurring because the dense scalar CIfTI intent code would not be recognized by the toolbox
- fix: fix a bug occurring when reading CIfTI file in Octave
- dev: add new tests that are covering CIfTI and GIfTI inputs
- dev: clean up several pieces of code (e.g., fix indentation inconsistencies, remove commented/unused pieces of code, rename variables, refactor the computation of cluster statistics,...)

### Link to relevant issues

- Issue #41
- Issue #161
- Issue #163
- Issue #168
- Issue #171
- Issue #173
- Issue #176

### CODE REVIEW

**Comment by nicholst** [comment]
Thanks @BryanGuillaume ! So happy this is rolling along!

**Comment by BryanGuillaume** [comment]
@nicholst, do you have any comments or things you want to check before I merge this PR and make the new release? If not, I will just wait for the tests to pass and go forward.

**Comment by nicholst** [comment]
Hey @BryanGuillaume 

You could merge but could you do some superficial tidying?  

All of your @swe_DataType files have no newline at end of file and the indenting is messed up on the comments -- mix of tabs and spaces; plus, a tab on an empty newline is regarded as bad practice; see:

Screenshot 2020-06-18 at 06 39 56

Also minor, but these lines [86](https://github.com/BryanGuillaume/SwE-toolbox/blob/new_release_2.2.1/swe_contrasts_WB.m#L86) and [88](https://github.com/BryanGuillaume/SwE-toolbox/blob/new_release_2.2.1/swe_contrasts_WB.m#L88) of swe_contrasts_WB.m have lots of trailing blanks that should go.  

Anyway, I checked out your new_release_2.2.1 branch and then did 
```
git diff v2.2.0
```
Can you just do these clean ups and fix all the 'no newline at end of files'?  It's minor but just good form. (Don't worry about every trailing space/tab it highlights in red... just the big/awkward ones like I found in swe_contrasts_SB.m)

Then it's good to go!

**Comment by nicholst** [comment]
Actually, these fixes are easy... these two one liners will fix everything:
```
for f in .travis.yml *.m */*.m ; do gsed -i 's/[ \t]*$//' $f; done
for f in .travis.yml *.m */*.m ; do gsed -i '$a\' $f; done
```
First one removes all trailing tabs and spaces, second one adds a final newline if its missing.

The gsed is required because the Mac version of sed doesn't work right.

ANYWAY, I just tried to do them on a branch of *your*  new_release_2.2.1 but when I tried to merge it (into your branch) it was all messed up.  I'll try later.

**Comment by BryanGuillaume** [comment]
@nicholst, thanks for your PR on my new_release_2.2.1 branch. I have merged it and I am now waiting for the tests to pass before merging this PR.

**Comment by nicholst** [comment]
It was failing but I couldn't see why...

**Comment by BryanGuillaume** [comment]
Maybe, it was because you were not authorized to merge a PR on my personal repo. I have added you as a collaborator, but it is now too late to try if this would have fixed the merging issue from your side.

**Pull request merged**
