### PR TITLE
More quotes

### PR DESCRIPTION
**Pull request by justbennet**
I got further along, and found a few more.  Then I ran grep looking for '("' and found one last set.

Sorry to have missed these first time round.

### CODE REVIEW

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have just seen these proposed updates! Thank you for your edits!

If it is okay with you though, I thought I had best just quickly double check the cause of this issue. The reason these quotes are double quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot and these sections of the code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

The variable `isOctave` here should tell us whether Octave or Matlab is being run. It should be equal to 1 is the code is being run inside Octave and 0 if it is being run inside Matlab. The isOctave variable is created as suggested in the official octave documentation [here](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) (see [Line 79](https://github.com/NISOx-BDI/SwE-toolbox/pull/66/files#diff-8464b4a3267760826308f04b9ab0175aR79) of `swe_cp_WB` for an example of how this was used). 

As a quick double check would you mind running the following lines of code on your matlab and let us know the output:

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

If you are in matlab this should be equal to 0 and octave it should be equal to 1. 

Another potential cause of this may be that double quotes did not exist before Matlab 2017a and I believe I saw on another post that you said you may be running Matlab 2016b. This could perhaps be causing a compiler error as the SwE toolbox was built to run on and has only been tested on the latest Matlab version. If possible, would you mind posting the error you obtain when you run this section of code as well?

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have just seen these proposed updates! Thank you for your edits!

If it is okay with you though, I thought I had best just quickly double check the cause of this issue. The reason these quotes are double quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot and these sections of the code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

The variable `isOctave` here should tell us whether Octave or Matlab is being run. It should be equal to 1 is the code is being run inside Octave and 0 if it is being run inside Matlab. The isOctave variable is created as suggested in the official octave documentation [here](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) (see [Line 79](https://github.com/NISOx-BDI/SwE-toolbox/pull/66/files#diff-8464b4a3267760826308f04b9ab0175aR79) of `swe_cp_WB` for an example of how this was used). 

As a quick double check would you mind running the following lines of code on your matlab and let us know the output:

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

If you are in matlab this should be equal to 0 and octave it should be equal to 1. 

Another potential cause of this may be that double quotes did not exist before Matlab 2017a and I believe I saw on another post that you said you may be running Matlab 2016b. This could perhaps be causing a compiler error as the SwE toolbox was built to run on and has only been tested on the latest Matlab version. If possible, would you mind posting the error you obtain when you run this section of code as well?

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have just seen these proposed updates! Thank you for your edits!

If it is okay with you though, I thought I had best just quickly double check the cause of this issue. The reason these quotes are double quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot and these sections of the code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

The variable `isOctave` here should tell us whether Octave or Matlab is being run. It should be equal to 1 is the code is being run inside Octave and 0 if it is being run inside Matlab. The isOctave variable is created as suggested in the official octave documentation [here](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) (see [Line 79](https://github.com/NISOx-BDI/SwE-toolbox/pull/66/files#diff-8464b4a3267760826308f04b9ab0175aR79) of `swe_cp_WB` for an example of how this was used). 

As a quick double check would you mind running the following lines of code on your matlab and let us know the output:

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

If you are in matlab this should be equal to 0 and octave it should be equal to 1. 

Another potential cause of this may be that double quotes did not exist before Matlab 2017a and I believe I saw on another post that you said you may be running Matlab 2016b. This could perhaps be causing a compiler error as the SwE toolbox was built to run on and has only been tested on the latest Matlab version. If possible, would you mind posting the error you obtain when you run this section of code as well?

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have just seen these proposed updates! Thank you for your edits!

If it is okay with you though, I thought I had best just quickly double check the cause of this issue. The reason these quotes are double quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot and these sections of the code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

The variable `isOctave` here should tell us whether Octave or Matlab is being run. It should be equal to 1 is the code is being run inside Octave and 0 if it is being run inside Matlab. The isOctave variable is created as suggested in the official octave documentation [here](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) (see [Line 79](https://github.com/NISOx-BDI/SwE-toolbox/pull/66/files#diff-8464b4a3267760826308f04b9ab0175aR79) of `swe_cp_WB` for an example of how this was used). 

As a quick double check would you mind running the following lines of code on your matlab and let us know the output:

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

If you are in matlab this should be equal to 0 and octave it should be equal to 1. 

Another potential cause of this may be that double quotes did not exist before Matlab 2017a and I believe I saw on another post that you said you may be running Matlab 2016b. This could perhaps be causing a compiler error as the SwE toolbox was built to run on and has only been tested on the latest Matlab version. If possible, would you mind posting the error you obtain when you run this section of code as well?

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have just seen these proposed updates! Thank you for your edits!

If it is okay with you though, I thought I had best just quickly double check the cause of this issue. The reason these quotes are double quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot and these sections of the code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

The variable `isOctave` here should tell us whether Octave or Matlab is being run. It should be equal to 1 is the code is being run inside Octave and 0 if it is being run inside Matlab. The isOctave variable is created as suggested in the official octave documentation [here](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) (see [Line 79](https://github.com/NISOx-BDI/SwE-toolbox/pull/66/files#diff-8464b4a3267760826308f04b9ab0175aR79) of `swe_cp_WB` for an example of how this was used). 

As a quick double check would you mind running the following lines of code on your matlab and let us know the output:

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

If you are in matlab this should be equal to 0 and octave it should be equal to 1. 

Another potential cause of this may be that double quotes did not exist before Matlab 2017a and I believe I saw on another post that you said you may be running Matlab 2016b. This could perhaps be causing a compiler error as the SwE toolbox was built to run on and has only been tested on the latest Matlab version. If possible, would you mind posting the error you obtain when you run this section of code as well?

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have just seen these proposed updates! Thank you for your edits!

If it is okay with you though, I thought I had best just quickly double check the cause of this issue. The reason these quotes are double quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot and these sections of the code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

The variable `isOctave` here should tell us whether Octave or Matlab is being run. It should be equal to 1 is the code is being run inside Octave and 0 if it is being run inside Matlab. The isOctave variable is created as suggested in the official octave documentation [here](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) (see [Line 79](https://github.com/NISOx-BDI/SwE-toolbox/pull/66/files#diff-8464b4a3267760826308f04b9ab0175aR79) of `swe_cp_WB` for an example of how this was used). 

As a quick double check would you mind running the following lines of code on your matlab and let us know the output:

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

If you are in matlab this should be equal to 0 and octave it should be equal to 1. 

Another potential cause of this may be that double quotes did not exist before Matlab 2017a and I believe I saw on another post that you said you may be running Matlab 2016b. This could perhaps be causing a compiler error as the SwE toolbox was built to run on and has only been tested on the latest Matlab version. If possible, would you mind posting the error you obtain when you run this section of code as well?

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have only just now seen your proposed updates! Thank you for edits!

Before merging anything I thought it might be best just to quickly double check a few things if it's okay by you. The reason these quotes are doubles quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot. These sections of code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

As a quick double check, would you mind quickly running the following lines of code on your matlab and let us know the output;

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

The variable `isOctave` here should tell us whether Matlab or Octave is being run and is based on the [suggested code](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) in the official Octave documentation. `isOctave` should be equal to 0 if the code is being run inside Matlab and 1 if the code is being run inside Octave. If this is being evaluated incorrectly it could cause the lines of code containing double quotes to be run and cause the errors you are experiencing.

If possible as well could you attach the error message you receive when running these lines of code. It may be that the lines of code containing the double quotes are not being run but rather cannot be compiled as double quotes did not exist in matlab before matlab version 2017a (I believe in another post you said you were running 2016b?). As the SwE toolbox has only been designed to run on and has only been tested on 2017b and above, this may also be the cause of the issue and the error message you are receiving may help us in identifying this.

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have only just now seen your proposed updates! Thank you for edits!

Before merging anything I thought it might be best just to quickly double check a few things if it's okay by you. The reason these quotes are doubles quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot. These sections of code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

As a quick double check, would you mind quickly running the following lines of code on your matlab and let us know the output;

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

The variable `isOctave` here should tell us whether Matlab or Octave is being run and is based on the [suggested code](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) in the official Octave documentation. `isOctave` should be equal to 0 if the code is being run inside Matlab and 1 if the code is being run inside Octave. If this is being evaluated incorrectly it could cause the lines of code containing double quotes to be run and cause the errors you are experiencing.

If possible as well could you attach the error message you receive when running these lines of code. It may be that the lines of code containing the double quotes are not being run but rather cannot be compiled as double quotes did not exist in matlab before matlab version 2017a (I believe in another post you said you were running 2016b?). As the SwE toolbox has only been designed to run on and has only been tested on 2017b and above, this may also be the cause of the issue and the error message you are receiving may help us in identifying this.

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have only just now seen your proposed updates! Thank you for edits!

Before merging anything I thought it might be best just to quickly double check a few things if it's okay by you. The reason these quotes are doubles quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot. These sections of code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

As a quick double check, would you mind quickly running the following lines of code on your matlab and let us know the output;

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

The variable `isOctave` here should tell us whether Matlab or Octave is being run and is based on the [suggested code](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) in the official Octave documentation. `isOctave` should be equal to 0 if the code is being run inside Matlab and 1 if the code is being run inside Octave. If this is being evaluated incorrectly it could cause the lines of code containing double quotes to be run and cause the errors you are experiencing.

If possible as well could you attach the error message you receive when running these lines of code. It may be that the lines of code containing the double quotes are not being run but rather cannot be compiled as double quotes did not exist in matlab before matlab version 2017a (I believe in another post you said you were running 2016b?). As the SwE toolbox has only been designed to run on and has only been tested on 2017b and above, this may also be the cause of the issue and the error message you are receiving may help us in identifying this.

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have only just now seen your proposed updates! Thank you for edits!

Before merging anything I thought it might be best just to quickly double check a few things if it's okay by you. The reason these quotes are doubles quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot. These sections of code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

As a quick double check, would you mind quickly running the following lines of code on your matlab and let us know the output;

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

The variable `isOctave` here should tell us whether Matlab or Octave is being run and is based on the [suggested code](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) in the official Octave documentation. `isOctave` should be equal to 0 if the code is being run inside Matlab and 1 if the code is being run inside Octave. If this is being evaluated incorrectly it could cause the lines of code containing double quotes to be run and cause the errors you are experiencing.

If possible as well could you attach the error message you receive when running these lines of code. It may be that the lines of code containing the double quotes are not being run but rather cannot be compiled as double quotes did not exist in matlab before matlab version 2017a (I believe in another post you said you were running 2016b?). As the SwE toolbox has only been designed to run on and has only been tested on 2017b and above, this may also be the cause of the issue and the error message you are receiving may help us in identifying this.

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have only just now seen your proposed updates! Thank you for edits!

Before merging anything I thought it might be best just to quickly double check a few things if it's okay by you. The reason these quotes are doubles quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot. These sections of code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

As a quick double check, would you mind quickly running the following lines of code on your matlab and let us know the output;

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

The variable `isOctave` here should tell us whether Matlab or Octave is being run and is based on the [suggested code](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) in the official Octave documentation. `isOctave` should be equal to 0 if the code is being run inside Matlab and 1 if the code is being run inside Octave. If this is being evaluated incorrectly it could cause the lines of code containing double quotes to be run and cause the errors you are experiencing.

If possible as well could you attach the error message you receive when running these lines of code. It may be that the lines of code containing the double quotes are not being run but rather cannot be compiled as double quotes did not exist in matlab before matlab version 2017a (I believe in another post you said you were running 2016b?). As the SwE toolbox has only been designed to run on and has only been tested on 2017b and above, this may also be the cause of the issue and the error message you are receiving may help us in identifying this.

**Comment by TomMaullin** [comment]
Hi @justbennet ,

Apologies I have only just now seen your proposed updates! Thank you for edits!

Before merging anything I thought it might be best just to quickly double check a few things if it's okay by you. The reason these quotes are doubles quotes is that in Octave single quotes and double quotes can be used interchangeably, whereas in Matlab they cannot. These sections of code were designed specifically to be run only in Octave. I had left these as double quotes as, if we find they are causing errors in matlab, they alert us to the fact the wrong section of code is being run.

As a quick double check, would you mind quickly running the following lines of code on your matlab and let us know the output;

```
isOctave = exist('OCTAVE_VERSION','builtin');
disp(isOctave);
```

The variable `isOctave` here should tell us whether Matlab or Octave is being run and is based on the [suggested code](https://octave.org/doc/v4.0.3/How-to-distinguish-between-Octave-and-Matlab_003f.html) in the official Octave documentation. `isOctave` should be equal to 0 if the code is being run inside Matlab and 1 if the code is being run inside Octave. If this is being evaluated incorrectly it could cause the lines of code containing double quotes to be run and cause the errors you are experiencing.

If possible as well could you attach the error message you receive when running these lines of code. It may be that the lines of code containing the double quotes are not being run but rather cannot be compiled as double quotes did not exist in matlab before matlab version 2017a (I believe in another post you said you were running 2016b?). As the SwE toolbox has only been designed to run on and has only been tested on 2017b and above, this may also be the cause of the issue and the error message you are receiving may help us in identifying this.

**Comment by justbennet** [comment]
@TomMaullin There seems to be something up with the mail, as I've got quite a few of these comments now.  That may be GitHub and nothing to be done, but I thought I'd mention it.

As for the `isOctave` sections, yes, sorry, I had meant to comment on them in the original e-mail I was going to send asking about this as an issue, but then I thought I would save you some work typing and just submit the PR.  Best intentions, and all that.

No, the `isOctave` does not appear to work in MATLAB R2016b.

```
>> isOctave = exist('OCTAVE_VERSION', 'builtin');
>> disp(isOctave)                                
```

This should be the error message that was generated by the first set of double-quotes.

```
Error: File: swe_cp_WB.m Line: 47 Column: 13
Creating a string using double quotes is not supported.  Use the string function.

Error in swe_cp (line 20)
          swe_cp_WB(SwE);

Error in swe_ui_main>run_Callback (line 146)
swe_cp

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in swe_ui_main (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)swe_ui_main('run_Callback',hObject,eventdata,guidata(hObject)) 
```

Execution stopped there.

I will have to install MATLAB R2018a on the machine to test it.  They will need it anyway if SwE-toolbox is unsupported in version earlier than 2017b.  I may be able to complete this today, but it may not be till tomorrow.

I don't know how GUI processing works, but something that uses

```
if verLessThan('matlab','9.3')
    fprintf('This version of MATLAB is not supported by the SwE toolbox.\n');
end
```

to warn users about old MATLAB versions might be a good addition?

I hope that's what you were needing.  I will be available to work on this more tomorrow, so let me know today if there is other testing you need done, and I'll try to fit it in.  Bear in mind that I am just the ignorant system administrator, so very detailed instructions for filling in any SwE parameters would be appreciated.  I have the one SWE.mat file and data that I can use, but otherwise I am pretty far at sea.

**Comment by nicholst** [comment]
Hi @justbennet,

Just a quick point of clarification.  By "doesn't work", what you mean?  I mean, what exactly is the output in response to these two lines?
```matlab
isOctave = exist('OCTAVE_VERSION', 'builtin');
disp(isOctave)                                
```
TIA!

**Comment by justbennet** [comment]
`isOctave` returned 0 in both cases.

The error about the double-quotes does not seem to appear when using MATLAB 2018a.

This is using the older, pre-change version that is labeled swe 1.2.10 but came in a file indicating 1.2.11.  I don't have the corresponding commit ID; sorry.

**Comment by justbennet** [comment]
The response to that command is 0; doesn't work as in, MATLAB still
produces an error about the use of double quotes instructing us to use
single quotes or the string() function.

```
                   R2016b (9.1.0.441655) 64-bit (glnxa64)
                             September 7, 2016
>> isOctave = exist('OCTAVE_VERSION', 'builtin');
>> disp(isOctave)
     0

```

**Pull request merged**
