### PR TITLE
'Classic' SwE fix

### PR DESCRIPTION
**Pull request by TomMaullin**
This PR aims to address the issues caused by using the 'classic' SwE setting as first reported by @justbennet in issue #68 .

### CODE REVIEW

**Comment by justbennet** [comment]
Hi, @TomMaullin, I applied the patches from the diff to our files.  It starts the estimation and got a bit less than 10% done according to the thermometer window, then it said this.

```
------------------------------------------------------------------------
Running job #1
------------------------------------------------------------------------
Running 'Run Model'
Initialising parameters                 :                        ...done
Output images                           :                  ...initialised
Plane   5/68 , block   1/1              :                  ...estimationFailed  'Run Model'
Dot indexing is not supported for variables of this type.
In file "/usr/local/matlab/SwE-toolbox/swe_cp_WB.m" (???), function "swe_hyptest" at line 2064.
In file "/usr/local/matlab/SwE-toolbox/swe_cp_WB.m" (???), function "swe_cp_WB" at line 858.
In file "/usr/local/matlab/SwE-toolbox/swe_cp.m" (???), function "swe_cp" at line 61.
In file "/usr/local/matlab/SwE-toolbox/swe_run_rmodel.m" (???), function "swe_run_rmodel" at line 22.

The following modules did not run:
Failed: Run Model
```

That appears to be at `nGr = length(unique(SwE.Gr.iGr));` in `swe_cp_WB.m`, which is referring to one of the variables that got put inside the 'if  isfield(SwE.type, 'modified')` conditional of the patch in this PR?

**Comment by TomMaullin** [comment]
Hi @justbennet , 

You are right yes! I am still currently working through each use case I have to check if I have caught all of these but I will ping you once these are all done if you would like and send out an email with a notification of the patch!

**Comment by justbennet** [comment]
If you don't mind sending the mail when you're done, that would be great.

I edited the files manually; I will see if I can figure out `git apply`.

Let me know when you would like me to give it another whirl, and I'll try
to do so, lickety-split.

One other, possibly trivial note, the main menu doesn't seem to size
properly for the fonts used, at least at my screen resolution.  Would you
like that in a separate issue?

**Comment by TomMaullin** [comment]
Hi @nicholst , 

I believe this PR should now fix all bugs related to the `classic` mode for SwE. Please let me know your thoughts on this update/if you are happy for me to merge this. In terms of releases, as this is a fairly major fix. my suggestion is we either do one more release before 2.0.0 which includes these updates or release 2.0.0 fairly soon.

@justbennet I believe this should now resolve the issues you were experiencing! Thanks again for finding this issue and all of your feedback and comments! Please do feel free to give the code from this branch a go and let us know what you think if you like! (Also, maybe the below will help/make things easier with downloading the modified code so that you don't have to apply the diff as you did before!)

```
git clone https://github.com/TomMaullin/SwE-Toolbox.git
git checkout -b modifiedFix
```

**Comment by nicholst** [comment]
Looks good!

**Comment by justbennet** [comment]
I pulled the master branch,

bennet@mistakenhat:/usr/local/matlab/SwE-toolbox$ git show | head -1
commit 43fcf6467650ff85595f1d3d7f3d16a938fda875

It completed, and I can get to the Display Results without errors.
This particular model did not show significant activation, so I don't
get a visual display, but I get no errors and presume I would have got
an error had there been a problem.

Thanks for the help!

**Comment by TomMaullin** [comment]
No worries! Thank you for the feedback!

**Pull request merged**
