### PR TITLE
WB display

### PR DESCRIPTION
**Pull request by TomMaullin**
This PR implements the display feature for wild bootstrap analyses.

### CODE REVIEW

**Comment by TomMaullin** [comment]
Hi @nicholst ,

The WB display is now working and this PR is now ready for review! To demonstrate it works and hasn't affected the previous display functions, I have included below some screenshots of the displays created under 4 different cases.

Case 1: Parametric, T contrast

image

Case 2: Parametric, F contrast

image

Case 3: Wild Bootstrap, T contrast

image

Case 4: Wild Bootstrap, F contrast

image

**Comment by nicholst** [comment]
Testing this now... ran into a few problems.  Not sure if they're specific to this PR, but they need to be addressed

I created a WB run with the Henson fMRI data (3 HRF basis coefficients, 12 subjects, 36 total scans).  SwEconfig (batch file save): [`SwE_config.mat`](https://www.dropbox.com/s/tts0pb5fjap284s/SwE_config.mat?dl=0).  I set a results directory *but* didn't take care to ensure that my PWD was the same as set in `swe.design.dir{1}`.  You know what happened?  When I executed the batch job started by "Specify Model" (as saved in `SwE_config.mat`), the [`SwE.mat`](https://www.dropbox.com/s/3jf0y8g0hcw2c5a/SwE.mat?dl=0) got created in the correct directory, but the output of "Run model" went to the current working directory!

It occurs to me while SPM's `SPM` structure has a `swd` at the top level, is it really the case that SwE's `SwE` doesn't have a corresponding `swd`?  Mine didn't.

**Comment by nicholst** [comment]
Next issue: 
In  `swe.design.WB.WB_yes.WB_nB` is 999 (the default), but when I did "Run model" it only got as far as 99:
```
Bootstrap # 96  Block 1/1               :  Elapsed time is 1.539202 seconds.
Bootstrap # 97  Block 1/1               :  Elapsed time is 1.550461 seconds.
Bootstrap # 98  Block 1/1               :  Elapsed time is 1.614926 seconds.
Bootstrap # 99  Block 1/1               :  Elapsed time is 1.617849 seconds.
                       ...done
Completed                               :          11:39:13 - 07/07/2018
...use the saved images for assessment
```
Also, notably, the 'thermometer bar' went to the top but then never reset... it's still got the spinning ball as I write.  However, I *was* then able to continue and do "Results".

**Comment by nicholst** [comment]
Next issue:  In results, the table looks great.  As far as I can tell it is correct (really would benefit from footer that tells you the number of Bootstraps, but that's a further enhancement).

One minor issue: There must be a missing semicolon somewhere b/c the following is spit out to the command line:

```
ans = 

  UIControl (hReg) with properties:

              Style: 'frame'
             String: ''
    BackgroundColor: [0.5800 0.7700 0.5700]
           Callback: ''
              Value: 0
           Position: [1.2111 1.2111 484.4444 230.1111]
              Units: 'pixels'

  Use GET to show all properties
```

**Comment by nicholst** [comment]
I'm going to stop here b/c I assume I shouldn't review #23 until this is sorted?

**Comment by TomMaullin** [comment]
```
Next issue:
In swe.design.WB.WB_yes.WB_nB is 999 (the default), but when I did "Run model" it only got as far as 99:

Bootstrap # 96  Block 1/1               :  Elapsed time is 1.539202 seconds.
Bootstrap # 97  Block 1/1               :  Elapsed time is 1.550461 seconds.
Bootstrap # 98  Block 1/1               :  Elapsed time is 1.614926 seconds.
Bootstrap # 99  Block 1/1               :  Elapsed time is 1.617849 seconds.
                       ...done
Completed                               :          11:39:13 - 07/07/2018
...use the saved images for assessment
Also, notably, the 'thermometer bar' went to the top but then never reset... it's still got the spinning ball as I write. However, I was then able to continue and do "Results".
```

Hi @nicholst ,

I have been unable to reproduce this bug - the below screenshots were taken from me running the batch configuration you sent with the only modifications being the directories in the paths:

image
image

Would you mind rerunning it and sending me the entire analysis directory i.e. all output scans and so forth as well as the SwE.mat file post-run (perhaps something in the code has modified the SwE at some stage during the "Run Model" stage). 

As for the spinning ball and the continual loading; sorry! I'll fix this right away!

**Comment by nicholst** [comment]
Huh... OK... I can't replicate it either now!  Sorry for the trouble!

I think the confusion is that SwE, when you click 'Run model', is looking for a SwE.mat (i.e. spm_select is told to look for it) and if the PWD has a SwE.mat then it is selected.  When I had the PWD in some other directory, I must have mistakenly clicked on it and run the wrong analysis.

**Comment by nicholst** [comment]
OK!  This looks good!  Now will look at #23

**Comment by TomMaullin** [comment]
Hi @nicholst ,

Ah okay I see - maybe this could have been caused by the swd bug looking at the wrong directory at some point! Regardless I'll fix the swd and GUI printout errors first thing tomorrow so that we can merge this branch!

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I believe all bugs discussed on this PR should now be fixed. Let me know if you are happy to merge!

**Pull request merged**
