### PR TITLE
Fix several CIfTI file issues 

### PR DESCRIPTION
**Pull request by BryanGuillaume**
The goal of this PR is to fix some issues observed with CIfTI files. Here below a summary of the fixes:

1. The XML files of the CIfTI inputs are now always copied in the CIfTI outputs. Before this PR, that was not the case.
2. The XML files of the CIfTI inputs with more than one contrast are modified in the outputs to set the number of time series to 1 (i.e. NumberOfSeriesPoints="1")
3. the nan values in the outputs have been replaced by zero values to avoid issues with CIFTI files

### CODE REVIEW

**Comment by BryanGuillaume** [comment]
I will wait for Travis to validate these changes. If Travis validates them, I will directly merge in order to make a new candidate release 2.2.0.rc2 as soon as possible.

**Comment by BryanGuillaume** [comment]
For information, I have been testing it on these changes on CIFTI parametric analyses, but I have not had the time to do the same on WB analyses.

**Comment by nicholst** [comment]
Thank you!

**Comment by BryanGuillaume** [comment]
mmm, I have some weird errors in Travis. For example:

```
Testing file: swe_vox_Tstat_c01.nii         
322error: verifyMapsUnchanged: mx_el_ne: nonconformant arguments (op1 is 153594x1, op2 is 51560x1)
```

This might be due to the fact that we are now using 0s instead of nans and thus, some file comparison are failing. I will investigate this in more details

**Comment by nicholst** [comment]
Awesome... only potential scary thing to check is about an edit to the XML
that changes its length.  Do you have example inputs with
2-digit NumberOfSeriesPoints, which you will then reduce to a 1-digit (i.e.
"1") value?  Will that mess anything up?

ALSO, are you aware that NIFTI vox_offset *must* be aligned to 16-byte word
boundaries?  See here
https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/vox_offset.html


It may be that CIFTI doesn't worry about this, but since SPM uses memory
mapping maybe it matters?  And, then, I won't know what you would do except
add spaces at the end of the XML maybe?

Anyway... just a gotcha to think about...

**Comment by BryanGuillaume** [comment]
Yes, that is a good point that made me a bit worried. Nevertheless, one change of this PR in @swe_cifti/private/write_hdr_raw.m consists of writing the XML file to the CIFTI file by adding 0s at the end (see [these lines](https://github.com/NISOx-BDI/SwE-toolbox/blob/a144fd93e1681e88e88c086fcd609970803426f9/%40swe_cifti/private/write_hdr_raw.m#L87-L94)). This should do a correct job taking into account the fact that when reading the XML files, the trailing zeros are actually set to empty characters (see [here](https://github.com/NISOx-BDI/SwE-toolbox/blob/b5fef5b19493ae11f2760bdc6336a2499108e588/%40swe_cifti/private/read_hdr_raw.m#L153)).

**Comment by BryanGuillaume** [comment]
While waiting for Travis, I have run a quick WB analysis with 99 bootstraps and everything seems fine ate first glance.

**Comment by BryanGuillaume** [comment]
All Travis tests have finally passed. I am merging this PR

**Comment by nicholst** [comment]
OK... extra NULL char's should be safe.  But, out of curiosity, in all of
the offsets you've seen in CIFTI's flavor of NIFTI, are they all multiples
of 16?  If so, it would seem important to ensure the continue to be so.

**Comment by BryanGuillaume** [comment]
Just replied on this topic to one of your emails. I am repeating the content below. Yes, I had three flavors of CIFTI outputs and all three give me the following for the offset:

vox_offset: 631936 = 16 * 39496
vox_offset: 657728 = 16 * 41108
vox_offset: 343232 = 16 * 21452

Thus, yes they are multiples of 16.

**Comment by nicholst** [comment]
Super!  And, since you're at most shrinking the length of the XML by one or
two bytes and add NULL padding at the end, you're never going to change the
actual value of the offset on writing out new CIFTIs, right?

**Pull request merged**
