### PR TITLE
Eigenvariates

### PR DESCRIPTION
**Pull request by TomMaullin**
This PR addresses issue #1 by adding an eigenvariate option to the display window.

### CODE REVIEW

**Comment by TomMaullin** [comment]
Use cases currently tested and working:

- [x] Parametric T
- [x] Parametric F 
- [x] Voxelwise Non-parametric T
- [ ] Voxelwise Non-parametric F
- [x] Clusterwise Non-parametric T
- [ ] Clusterwise Non-parametric F
- [x] TFCE Non-parametric T
- [ ] TFCE Non-parametric F

**Comment by TomMaullin** [comment]
Hi @nicholst , 

I believe this PR should fix the eigenvariates issue! However, as I have never touched this code before, a second opinion on the changes I have made would be greatly appreciated! 

I have tested fairly thoroughly the main use-cases (see the list in the above comment) but it is difficult to cover all options at this point and verify the correctness of what I have implemented. For this reason I have tried to use the SPM code as much as possible. Please, if you're able at some point, give this a try and let me know your thoughts!

One major change this PR required which is worth mentioning was that the beta maps are now output for all WB analyses (previously these were only retained for parametric analyses) as the beta values were required by `swe_regions` on [line 203](https://github.com/TomMaullin/SwE-toolbox/blob/Eigenvariates/swe_regions.m#L203). For this reason I have also had to update the ground truth for the tests to include beta maps (all files that already exist in the ground truth folders have been left untouched). The corresponding PR for the additional maps in the ground truth can be found [here](https://github.com/NISOx-BDI/SwE-toolbox-testdata/pull/3).

**Comment by nicholst** [comment]
Looks good!  See my PR onto your branch, https://github.com/TomMaullin/SwE-toolbox/pull/13

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I have now merged your edits and can confirm all tests pass. I am happy to merge this branch when you are!

**Comment by nicholst** [comment]
This is good to go!

**Comment by TomMaullin** [comment]
Okay great! Thanks @nicholst !

**Pull request merged**
